auto: true

# markdown: kramdown 
markdown: rdiscount 
# markdown: redcarpet 
highlighter: rouge
# highlighter: pygemts
paginate: 10
paginate_path: "/page:num/"
permalink: date

kramdown:
    enable_coderay: true
    input: GFM

title: shuaqiu
url: http://shuaqiu.github.io
feed: /shuaqiu.xml
author:
    name: shuaqiu
    weibo: http://weibo.com/beautifulpursuer
description: "shuaqiu"
author_info: <a href="http://shuaqiu.github.io/about">shuaqiu</a>

copyright:
    - Design by <a href="http://shuaqiu.github.io/about" title="shuaqiu" target="_blank">shuaqiu</a> &copy; Copyright 2012
