auto: true

markdown: rdiscount
pygments: true
paginate: 10
paginate_path: "/page:num/"
permalink: date

title: shuaqiu
url: http://shuaqiu.github.io
feed: /shuaqiu.xml
author:
    name: shuaqiu
    weibo: http://weibo.com/beautifulpursuer
description: "shuaqiu"
author_info: <a href="http://shuaqiu.github.io/about">shuaqiu</a>

copyright:
    - Design by <a href="http://shuaqiu.github.io/about" title="shuaqiu" target="_blank">shuaqiu</a> &copy; Copyright 2012
